ARMOUR_TRIM_TRANSFORMER = {
    "ward_trim": "ward_armor_trim_smithing_template",
    "spire_trim": "spire_armor_trim_smithing_template",
    "coast_trim": "coast_armor_trim_smithing_template",
    "eye_trim": "eye_armor_trim_smithing_template",
    "dune_trim": "dune_armor_trim_smithing_template",
    "wild_trim": "wild_armor_trim_smithing_template",
    "rib_trim": "rib_armor_trim_smithing_template",
    "tide_trim": "tide_armor_trim_smithing_template",
    "sentry_trim": "sentry_armor_trim_smithing_template",
    "vex_trim": "vex_armor_trim_smithing_template",
    "snout_trim": "snout_armor_trim_smithing_template",
    "wayfinder_trim": "wayfinder_armor_trim_smithing_template",
    "sharper_trim": "sharper_armor_trim_smithing_template",
    "silence_trim": "silence_armor_trim_smithing_template",
    "raiser_trim": "raiser_armor_trim_smithing_template",
    "host_trim": "host_armor_trim_smithing_template",
    "flow_trim": "flow_armor_trim_smithing_template",
    "bolt_trim": "bolt_armor_trim_smithing_template",
}

POTTERY_SHERD_TRANSFORMER = {
    "angler_sherd": "angler_pottery_sherd",
    "archer_sherd": "archer_pottery_sherd",
    "arms_up_sherd": "arms_up_pottery_sherd",
    "blade_sherd": "blade_pottery_sherd",
    "brewer_sherd": "brewer_pottery_sherd",
    "burn_sherd": "burn_pottery_sherd",
    "danger_sherd": "danger_pottery_sherd",
    "explorer_sherd": "explorer_pottery_sherd",
    "friend_sherd": "friend_pottery_sherd",
    "heart_sherd": "heart_pottery_sherd",
    "heartbreak_sherd": "heartbreak_pottery_sherd",
    "howl_sherd": "howl_pottery_sherd",
    "miner_sherd": "miner_pottery_sherd",
    "mourner_sherd": "mourner_pottery_sherd",
    "plenty_sherd": "plenty_pottery_sherd",
    "prize_sherd": "prize_pottery_sherd",
    "sheaf_sherd": "sheaf_pottery_sherd",
    "shelter_sherd": "shelter_pottery_sherd",
    "skull_sherd": "skull_pottery_sherd",
    "snort_sherd": "snort_pottery_sherd",
    "flow_sherd": "flow_pottery_sherd",
    "guster_sherd": "guster_pottery_sherd",
    "scrape_sherd": "scrape_pottery_sherd",
}

MISC_ITEM_TRANSFORMER = {
    "crimson_log": "crimson_stem",
    "warped_log": "warped_stem",
    "block_of_quartz": "quartz_block",
    "pot": "decorated_pot",
    "cherry_blossoms_leave": "cherry_leaves",
    "glowberry": "glow_berries",
    "flowering_azalea_bush": "flowering_azalea",
    "azalea_bush": "azalea",
    "horse_armor": "leather_horse_armor",
    "nametag": "name_tag",
    "totem": "totem_of_undying",
    "netherite_upgrade": "netherite_upgrade_smithing_template",
    "turtle_shell": "turtle_helmet",
    "glow_ink": "glow_ink_sac",
    "nether_quartz": "quartz",
    "stonebrick": "stone_brick",
    "blazerod": "blaze_rod",
    "mud_brick": "mud_bricks",
    "rocket": "firework_rocket",
}
