from typing import List, FrozenSet

"""
Minecraft Items and Blocks Constants Module
Contains organized groupings of items, blocks, and their variants.
"""

# Base colors used throughout the game
COLORS: List[str] = [
    "white",
    "light_gray",
    "gray",
    "black",
    "brown",
    "red",
    "orange",
    "yellow",
    "lime",
    "green",
    "cyan",
    "light_blue",
    "blue",
    "purple",
    "magenta",
    "pink",
]

# Non-categorizable or special items
UNFILTERABLE_ITEMS: FrozenSet[str] = frozenset(
    [
        "diamond_armor",
        "llama",
        "mule",
        "exp",
        "enchanted_bow",
        "enchantment_book",
        "enchanted_book",
        "misc_item",
        "enchantment_service",
        "villager_trading",
        "brown_wolves",
        "casino",
        "horse",
        "card_delivery",
        "potion",
        "respiration",
        "swift_sneak",
        "music_disc",
        "diamond_tool",
        "unbreaking",
        "mending",
        "soul_speed",
        "mini_block",
        "regeneration_potion",
        "halloween_garland_map_art",
        "carved_pumpkin_map_art",
        "map_art_sticker",
        '"oh_shit_box"',
        "enchanted_tool",
        "enchanted_armor",
        "diamond_armour",
        "guardian_head",
        "swift_sneak_3",
        "map_art",
        "ore",
        "phantom_head",
        "teleportation_service",
        "pokemon_card",
        "mob_head",
        "glow_squid_head",
        "renewable_lava_shulker",
        "magma_cube_head",
        "iron_golem_head",
        "vending_machine",
        "hoglin_head",
        "food",
        "plushie",
        "elytra_box",
        "villager_trading_hall",
        "custom_head",
    ]
)

# Armor trim patterns
ARMOUR_TRIMS: FrozenSet[str] = frozenset(
    f"{trim}__armor_trim_smithing_template"
    for trim in [
        "ward",
        "spire",
        "coast",
        "eye",
        "dune",
        "wild",
        "rib",
        "tide",
        "sentry",
        "vex",
        "snout",
        "wayfinder",
        "sharper",
        "silence",
        "raiser",
        "host",
        "flow",
        "bolt",
    ]
)

# Pottery sherd patterns
POTTERY_SHERDS: FrozenSet[str] = frozenset(
    f"{sherd}_pottery_sherd"
    for sherd in [
        "angler",
        "archer",
        "arms_up",
        "blade",
        "brewer",
        "burn",
        "danger",
        "explorer",
        "friend",
        "heart",
        "heartbreak",
        "howl",
        "miner",
        "mourner",
        "plenty",
        "prize",
        "sheaf",
        "shelter",
        "skull",
        "snort",
        "flow",
        "guster",
        "scrape",
    ]
)

# Light sources
FROGLIGHTS: FrozenSet[str] = frozenset(
    f"{froglight}_froglight" for froglight in ["ochre", "pearlescent", "verdant"]
)

# Flowers and decorative plants
FLOWERS: FrozenSet[str] = frozenset(
    [
        "dandelion",
        "poppy",
        "allium",
        "cornflower",
        "blue_orchid",
        "oxeye_daisy",
        "azure_bluet",
        "pink_petals",
        "peony",
        "rose_bush",
        "lilac",
        "sunflower",
        "lily_of_the_valley",
        "red_tulip",
        "orange_tulip",
        "white_tulip",
        "pink_tulip",
        "closed_eyeblossom",
        "open_eyeblossom",
    ]
)

# Color-based blocks
WOOL: frozenset[str] = frozenset(f"{color}_wool" for color in COLORS)
DYES: frozenset[str] = frozenset(f"{color}_dye" for color in COLORS)
CONCRETE: frozenset[str] = frozenset(f"{color}_concrete" for color in COLORS)
CONCRETE_POWDER: frozenset[str] = frozenset(
    f"{color}_concrete_powder" for color in COLORS
)
GLAZED_TERRACOTTA: frozenset[str] = frozenset(
    f"{color}_glazed_terracotta" for color in COLORS
)
STAINED_GLASS_PANE: frozenset[str] = frozenset(
    f"{color}_stained_glass_pane" for color in COLORS
)
STAINED_GLASS: frozenset[str] = frozenset(f"{color}_stained_glass" for color in COLORS)
BANNERS: frozenset[str] = frozenset(f"{color}_banner" for color in COLORS)
CORAL: frozenset[str] = frozenset(
    [
        "brain_coral_block",
        "brain_coral_fan",
        "brain_coral",
        "tube_coral_block",
        "tube_coral_fan",
        "tube_coral",
        "horn_coral_block",
        "horn_coral_fan",
        "horn_coral",
        "fire_coral_block",
        "fire_coral_fan",
        "fire_coral",
        "bubble_coral_block",
        "bubble_coral_fan",
        "bubble_coral",
    ]
)

# Blocks that grammatically end with 's'
BLOCKS_ENDS_WITH_S: FrozenSet[str] = frozenset(
    [
        "acacia_leaves",
        "acacia_planks",
        "acacia_stairs",
        "ancient_debris",
        "andesite_stairs",
        "azalea_leaves",
        "bamboo_planks",
        "bamboo_stairs",
        "beetroot_seeds",
        "birch_leaves",
        "birch_planks",
        "birch_stairs",
        "blackstone_stairs",
        "black_stained_glass",
        "blue_stained_glass",
        "bricks",
        "brick_stairs",
        "brown_stained_glass",
        "cactus",
        "chainmail_boots",
        "chainmail_leggings",
        "cherry_leaves",
        "cherry_planks",
        "cherry_stairs",
        "chiseled_nether_bricks",
        "chiseled_stone_bricks",
        "chiseled_tuff_bricks",
        "cobbled_deepslate_stairs",
        "cobblestone_stairs",
        "cocoa_beans",
        "compass",
        "cracked_deepslate_bricks",
        "cracked_nether_bricks",
        "cracked_polished_blackstone_bricks",
        "cracked_stone_bricks",
        "crimson_fungus",
        "crimson_planks",
        "crimson_roots",
        "crimson_stairs",
        "cut_copper_stairs",
        "cyan_stained_glass",
        "dark_oak_leaves",
        "dark_oak_planks",
        "dark_oak_stairs",
        "dark_prismarine_stairs",
        "deepslate_bricks",
        "deepslate_brick_stairs",
        "diamond_boots",
        "diamond_leggings",
        "diorite_stairs",
        "end_stone_bricks",
        "end_stone_brick_stairs",
        "expoded_cut_copper_stairs",
        "flowering_azalea_leaves",
        "glass",
        "glow_berries",
        "golden_boots",
        "golden_leggings",
        "granite_stairs",
        "gray_stained_glass",
        "green_stained_glass",
        "hanging_roots",
        "iron_bars",
        "iron_boots",
        "iron_leggings",
        "jungle_leaves",
        "jungle_planks",
        "jungle_stairs",
        "leather_boots",
        "leather_leggings",
        "light_blue_stained_glass",
        "light_gray_stained_glass",
        "lime_stained_glass",
        "magenta_stained_glass",
        "mangrove_leaves",
        "mangrove_planks",
        "mangrove_stairs",
        "mangrove_roots",
        "melon_seeds",
        "mossy_stone_bricks",
        "mossy_stone_brick_stairs",
        "mud_bricks",
        "mud_brick_stairs",
        "music_disc_blocks",
        "netherite_boots",
        "netherite_leggings",
        "nether_bricks",
        "nether_brick_stairs",
        "nether_sprouts",
        "oak_leaves",
        "oak_planks",
        "oak_stairs",
        "orange_stained_glass",
        "oxidized_cut_copper_stairs",
        "pink_petals",
        "pink_stained_glass",
        "polished_andesite_stairs",
        "polished_blackstone_bricks",
        "polished_blackstone_brick_stairs",
        "polished_blackstone_stairs",
        "polished_deepslate_stairs",
        "polished_diorite_stairs",
        "polished_granite_stairs",
        "polished_tuff_stairs",
        "prismarine_bricks",
        "prismarine_brick_stairs",
        "prismarine_crystals",
        "prismarine_stairs",
        "pumpkin_seeds",
        "purple_stained_glass",
        "purpur_stairs",
        "quartz_bricks",
        "quartz_stairs",
        "recovery_compass",
        "red_nether_bricks",
        "red_nether_brick_stairs",
        "red_sandstone_stairs",
        "red_stained_glass",
        "sandstone_stairs",
        "seagrass",
        "shears",
        "short_grass",
        "smooth_quartz_stairs",
        "smooth_red_sandstone_stairs",
        "smooth_sandstone_stairs",
        "spruce_leaves",
        "spruce_planks",
        "spruce_stairs",
        "spyglass",
        "stone_bricks",
        "stone_brick_stairs",
        "stone_stairs",
        "sweet_berries",
        "tall_grass",
        "tinted_glass",
        "torchflower_seeds",
        "tuff_bricks",
        "tuff_brick_stairs",
        "tuff_stairs",
        "twisting_vines",
        "warped_fungus",
        "warped_planks",
        "warped_roots",
        "warped_stairs",
        "waxed_cut_copper_stairs",
        "waxed_exposed_cut_copper_stairs",
        "waxed_oxidized_cut_copper_stairs",
        "waxed_weathered_cut_copper_stairs",
        "weathered_cut_copper_stairs",
        "weeping_vines",
        "wheat_seeds",
        "white_stained_glass",
        "yellow_stained_glass",
        "pale_oak_leaves",
        "pale_moss",
        "pale_hanging_moss",
        "hanging_roots",
    ]
)
